spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/userRole
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
